#!/bin/bash

export $(grep -v '^#' .env | xargs -d '\n')

echo "DEPLOYMENT_DIR=$DEPLOYMENT_DIR"
echo "L1_RPC_URL=$L1_RPC_URL"
echo "L1_EXPLORER_HOST=$L1_EXPLORER_HOST"
echo "L1_APP_HOST=$L1_APP_HOST"
echo "L1_STATS_API_URL=$L1_STATS_API_URL"
echo "L1_VISUALIZE_API_URL=$L1_VISUALIZE_API_URL"
echo "L1_IS_TESTNET=$L1_IS_TESTNET"
echo "L1_CHAIN_ID=$L1_CHAIN_ID"
echo "L1_NETWORK_NAME=$L1_NETWORK_NAME"
echo "L1_NETWORK_SHORT_NAME=$L1_NETWORK_SHORT_NAME"
echo "L1_CURRENCY_NAME=$L1_CURRENCY_NAME"
echo "L1_CURRENCY_SYMBOL=$L1_CURRENCY_SYMBOL"